# Standard
import hashlib
import random

# Wandb-style adjectives (positive, descriptive)
ADJECTIVES = [
    "able",
    "ancient",
    "autumn",
    "bold",
    "brave",
    "bright",
    "calm",
    "clean",
    "clever",
    "cool",
    "cosmic",
    "daily",
    "dark",
    "deep",
    "divine",
    "dry",
    "eager",
    "early",
    "earnest",
    "easy",
    "epic",
    "even",
    "exact",
    "fair",
    "fast",
    "fine",
    "firm",
    "first",
    "fresh",
    "full",
    "gentle",
    "glad",
    "golden",
    "good",
    "great",
    "green",
    "happy",
    "hard",
    "heavy",
    "high",
    "holy",
    "huge",
    "jolly",
    "keen",
    "kind",
    "large",
    "late",
    "light",
    "live",
    "long",
    "loud",
    "lucky",
    "major",
    "mild",
    "new",
    "nice",
    "noble",
    "old",
    "open",
    "plain",
    "proud",
    "pure",
    "quick",
    "quiet",
    "rapid",
    "rare",
    "real",
    "rich",
    "right",
    "rough",
    "round",
    "safe",
    "sharp",
    "short",
    "simple",
    "slow",
    "small",
    "smart",
    "smooth",
    "soft",
    "solid",
    "strong",
    "sure",
    "swift",
    "tall",
    "thick",
    "thin",
    "tiny",
    "true",
    "vast",
    "warm",
    "weak",
    "whole",
    "wide",
    "wild",
    "wise",
    "young",
    "exalted",
    "legendary",
    "resilient",
    "vibrant",
    "stellar",
    "graceful",
    "radiant",
    "serene",
    "brilliant",
    "majestic",
    "elegant",
]

# Wandb-style nouns (nature, objects, concepts)
NOUNS = [
    "abyss",
    "angel",
    "arrow",
    "atom",
    "ball",
    "band",
    "bark",
    "beam",
    "bear",
    "bell",
    "bird",
    "bloom",
    "blue",
    "boat",
    "bone",
    "book",
    "brook",
    "brush",
    "calm",
    "cave",
    "cell",
    "chant",
    "chord",
    "clay",
    "cliff",
    "cloud",
    "coal",
    "coast",
    "coin",
    "colt",
    "coral",
    "core",
    "creek",
    "crop",
    "crown",
    "cube",
    "dawn",
    "day",
    "dew",
    "disk",
    "dove",
    "dream",
    "drop",
    "dust",
    "eagle",
    "earth",
    "echo",
    "edge",
    "ember",
    "field",
    "fire",
    "fish",
    "flame",
    "flight",
    "flow",
    "foam",
    "fog",
    "forest",
    "frost",
    "glow",
    "gold",
    "grass",
    "grove",
    "haze",
    "heart",
    "hill",
    "ice",
    "iris",
    "jade",
    "lake",
    "land",
    "leaf",
    "light",
    "lion",
    "moon",
    "moss",
    "night",
    "oak",
    "ocean",
    "path",
    "peak",
    "pearl",
    "pine",
    "pond",
    "rain",
    "reef",
    "river",
    "rock",
    "rose",
    "sage",
    "sand",
    "sea",
    "shadow",
    "shore",
    "sky",
    "snow",
    "song",
    "star",
    "stone",
    "storm",
    "stream",
    "sun",
    "sunset",
    "surf",
    "tide",
    "tree",
    "vale",
    "wave",
    "wind",
    "wing",
    "wolf",
    "wood",
    "darkness",
    "meadow",
    "thunder",
    "crystal",
    "valley",
    "mountain",
]


def get_flow_identifier(name: str) -> str:
    """Generate a deterministic wandb-style flow identifier.

    Creates a human-readable identifier in the format "adjective-noun-number"
    that is deterministic based on the input name. Same name will always
    produce the same identifier.

    Args:
        name: Flow name to generate identifier from

    Returns:
        A string in the format "adjective-noun-number" (e.g., "bright-river-123")

    Examples:
        >>> get_flow_identifier("My Document QA Flow")
        "bright-river-123"
        >>> get_flow_identifier("My Document QA Flow")  # Same input
        "bright-river-123"  # Same output
    """
    # Create deterministic seed from name
    seed_value = int(hashlib.sha256(name.encode()).hexdigest()[:8], 16)
    rng = random.Random(seed_value)

    # Select words and number deterministically
    adjective = rng.choice(ADJECTIVES)
    noun = rng.choice(NOUNS)
    number = rng.randint(1, 999)

    return f"{adjective}-{noun}-{number}"
