# SPDX-License-Identifier: Apache-2.0

name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release-**"
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'tox.ini'
      - '.github/workflows/test.yml' # This workflow
  pull_request:
    branches:
      - "main"
      - "release-**"
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'tox.ini'
      - '.github/workflows/test.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    name: "Unit Tests - ${{ matrix.python }} on ${{ matrix.platform }}"
    runs-on: "${{ matrix.platform }}"
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
        platform:
          - "ubuntu-latest"
        include:
          - python: "3.11"
            platform: "macos-latest"
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # https://github.com/actions/checkout/issues/249
          fetch-depth: 0

      - name: Free disk space
        if: matrix.platform != 'macos-latest'
        uses: ./.github/actions/free-disk-space

      - name: Install the expect package
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get install -y expect

      - name: Install tools on MacOS
        if: startsWith(matrix.platform, 'macos')
        run: |
          brew install expect coreutils bash

      - name: Setup uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version: "0.10.1"
          python-version: ${{ matrix.python }}
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Install tox with tox-uv
        run: |
          uv tool install tox --with tox-uv --with tox-gh

      - name: Run unit tests with tox
        run: |
          tox -e py3-unitcov


      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true

      - name: Prune uv cache
        run: uv cache prune --ci

  test-workflow-complete:
    needs: ["test"]
    runs-on: ubuntu-latest
    steps:
      - name: Test Workflow Complete
        run: echo "Test Workflow Complete"
